CREATE TABLE IF NOT EXISTS `users` (
  ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `Name` VARCHAR(249),
  Email VARCHAR(249),
  Password VARCHAR(249),
  Bio VARCHAR(249),
  ImageLink VARCHAR(249),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);